import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import { ThemeContextProvider } from "@/Context/ThemeContext";
import ThemeProvider from "@/providers/Themeproviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <ThemeProvider>
            <div className="container">
              <div className="wrapper">
                <NavBar />
                {children}
              </div>
            </div>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
