import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import { ThemeContextProvider } from "@/Context/ThemeContext";
import ThemeProvider from "@/providers/Themeproviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden max-w-screen">
        <ThemeContextProvider>
          <ThemeProvider>
            <div className=" min-h-screen  bg-custom-bg  text-custom-text  w-screen overflow-x-hidden">
              <div className=" max-w-475 sm:max-w-640 2xl:max-w-1536 xl:max-w-1366 lg:max-w-1024 md:max-w-768  mx-auto px-80 justify-center ">
                <NavBar />
                {children}
              </div>
            </div>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
